# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'LuckyLoan' do
  use_frameworks!
  pod 'AFNetworking', '~> 4.0'
  pod 'MJExtension', '3.2.1'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'
  pod 'YYText', '1.0.7'
  pod 'SDWebImage', '>= 5.0.0'
  pod 'TZImagePickerController'
  pod 'AppsFlyerFramework', '~> 6.12.0'
end
